#:schema https://json.schemastore.org/hugo.json

# Basic config
baseURL = 'https://www.anhkhoakz.dev/'
copyright = 'anhkhoakz'
defaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'anhkhoakz personal blog'
enableEmoji = true


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles.
[markup]
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true

# Multilingual mode config.
[languages]
[languages.en]
LanguageCode = "en-US"
contentDir = "content"
languageName = "en-US 🇺🇸"
title = "anhkhoakz"


[params]
description = "anhkhoakz personal blog"
disableComments = false
subtitle = "anhkhoakz personal blog"


# These images will show up when services want to generate a preview of a link
# to your site. Ignored if `generateSocialCard = true`. For more information
# about previews, see https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph
images = ["images/share.webp"]

dateFormat = "02/01/06"

hideUntranslated = true

# (EXPERIMENTAL) This themehas two options for its CSS styles: "original" and
# "herman". The former is what you see on Bear Cub's demo (an optimized
# version of Hugo Bear Blog), while the latter has a more modern look based on
# Herman Martinus's version of the Blogster Minimal theme for Astro.
theme = "hugo-bearcub"
themeStyle = "herman"

# (EXPERIMENTAL) This theme is capable of dynamically generating social cards
# for posts that don't have `images` defined in their front matter; By setting
# `generateSocialCard` to false, you can prevent this behavior. For more
# information see layouts/partials/social_card.html
generateSocialCard = false

# Social media. Delete any item you aren't using to make sure it won't show up
# in your website's metadata.
[params.social]
github = "anhkhoakz"


# Author metadata. This is mostly used for the RSS feed of your site, but the
# email is also added to the footer of each post. You can hide the "reply to"
# link by using a `hideReply` param in front matter.
[params.author]
email = "dose_untie091@aleeas.com"
name = "anhkhoakz"

[params.contact]
email = "dose_untie091@aleeas.com"

[params.favicon]
light = "images/favicon.webp"
dark = "images/favicon-dark.webp"


# Privacy settings

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true
[privacy.instagram]
disable = false
simple = true
[privacy.vimeo]
disable = false
enableDNT = true
simple = true
[privacy.x]
disable = false
enableDNT = true
simple = true
[privacy.youTube]
disable = false
privacyEnhanced = true
simple = true


[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[security]
[security.http]
methods = ["(?i)GET"]
urls = [".*"]

[services]
[services.rss]
limit = -1
