name: Deploy pages

on:
  # Daily build to catch any future-dated posts
  schedule:
    - cron: 0 0 * * *

  # Build on pushes to the main branch only
  push:
    branches:
      - main

concurrency:
  group: deploy-pages

  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Build and deploy Hugo site

    runs-on: ubuntu-latest

    steps:
      # Install Hugo in the runner
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "latest"
          extended: true

      # Check out the source for the site
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Build the site with Hugo with baseURL https://anhkhoakz.neocities.org/
      - name: Build with Hugo
        run: hugo --minify --baseURL https://anhkhoakz.neocities.org/

      # Push the rendered site to Neocities and clean up any orphaned files
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public

      # Build the site with Hugo with baseURL https://anhkhoakz.surge.sh/
      - name: Build with Hugo
        run: hugo --minify --baseURL https://anhkhoakz.surge.sh/

      # Push the rendered site to Surge
      - name: Deploy to Surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "anhkhoakz.surge.sh"
          project: "public"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
