name: Mirroring

on: [push, delete]

jobs:
  to_codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@codeberg.org:anhkhoakz/pages.git
          ssh_private_key:
            ${{ secrets.codeberg_ssh }}

  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:anhkhoakz/my-website.git
          ssh_private_key:
            ${{ secrets.gitlab_ssh }}

  to_framagit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@framagit.org:anhkhoakz/my-website.git
          ssh_private_key:
            ${{ secrets.framagit_ssh }}

  to_sourcehut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@git.sr.ht:~anhkhoakz/pages
          ssh_private_key:
            ${{ secrets.sourcehut_ssh }}

  to_notabug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@notabug.org:anhkhoakz/pages.git
          ssh_private_key:
            ${{ secrets.notabug_ssh }}
