name: Mirroring

on: [push, delete]

jobs:

  to_codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure 1Password
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Mirroring to Codeberg
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TOKEN }}
          target_repo_url: git@codeberg.org:anhkhoakz/anhkhoakz.github.io.git
          ssh_private_key: ${{ secrets.OP_CODEBERG_PRIVATE_KEY }}

  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure 1Password
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Mirroring to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TOKEN }}
          target_repo_url: git@gitlab.com:anhkhoakz/my-website.git
          ssh_private_key: ${{ secrets.OP_GITLAB_PRIVATE_KEY }}

  to_framagit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure 1Password
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Mirroring to Framagit
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TOKEN }}
          target_repo_url: git@framagit.org:anhkhoakz/my-website.git
          ssh_private_key: ${{ secrets.OP_FRAMAGIT_PRIVATE_KEY }}
