name: Mirroring

on: [push, delete]

jobs:

  to_codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Load secrets 1Password
        uses: 
          1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TOKEN }}
          ssh_private_key: op://Security/Codeberg/private key
      - name: Mirroring to Codeberg
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:anhkhoakz/anhkhoakz.github.io.git